"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()


def _lista_do_ambiente(nome):
    """Lista separada por vírgulas: remove espaços, itens vazios e duplicados."""
    itens = (item.strip() for item in os.getenv(nome, "").split(","))
    return list(dict.fromkeys(item for item in itens if item))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

# Hosts e origens vêm do ambiente (DJANGO_ALLOWED_HOSTS e
# DJANGO_CSRF_TRUSTED_ORIGINS, separados por vírgula). No Render, o hostname
# externo (RENDER_EXTERNAL_HOSTNAME, definido pela plataforma) entra sozinho.
# Com DEBUG=True e lista vazia, o Django já aceita localhost e 127.0.0.1.
ALLOWED_HOSTS = _lista_do_ambiente("DJANGO_ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = _lista_do_ambiente("DJANGO_CSRF_TRUSTED_ORIGINS")

_render_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if _render_hostname:
    ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, _render_hostname]))
    CSRF_TRUSTED_ORIGINS = list(
        dict.fromkeys([*CSRF_TRUSTED_ORIGINS, f"https://{_render_hostname}"])
    )

# HTTPS
# O Render termina o TLS no proxy e informa o protocolo original neste
# cabeçalho; sem ele, o Django veria HTTP e recusaria o CSRF do login.
# HSTS e redirecionamento HTTP→HTTPS ficam com a plataforma (ver 34.7).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Cookies só por HTTPS em produção; em desenvolvimento (DEBUG=True) o login
# continua funcionando em http://127.0.0.1. HttpOnly segue o padrão do Django.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition
# MVP da N2 - Etapa 1 sem banco de dados: sem admin, auth, contenttypes,
# sessions (app), messages nem models próprios.

INSTALLED_APPS = [
    'django.contrib.staticfiles',

    # Apps do projeto
    'documentos',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serve os arquivos estáticos em produção (sem servidor web separado).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# Nenhum banco: o Django usa o backend "dummy", que recusa qualquer consulta.

DATABASES = {}


# Sessão
# Cookie assinado (sem banco). Guarda só o indicador do login da demonstração.

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Destino do collectstatic (build). Não versionado (.gitignore).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Em produção, WhiteNoise com nomes com hash e compressão (exige collectstatic).
# Em desenvolvimento e nos testes, o storage simples do Django, que não depende
# do manifesto. "default" mantém o alias padrão; nenhum arquivo é gravado nele.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# Limite máximo para upload de PDFs (o PDF não é gravado; só é lido na requisição)

MAX_PDF_UPLOAD_SIZE_MB = int(os.getenv("MAX_PDF_UPLOAD_SIZE_MB", "10"))
MAX_PDF_UPLOAD_SIZE = MAX_PDF_UPLOAD_SIZE_MB * 1024 * 1024

# Gemini
# A validação acontece somente quando agents.gemini_client.GeminiClient é criado.
# Não há GEMINI_API_KEY aqui: a chave é informada na tela a cada processamento
# e só existe durante a requisição. Só as configurações não secretas vêm do ambiente.

GEMINI_MODEL = os.getenv("GEMINI_MODEL")
GEMINI_TIMEOUT_SEGUNDOS = os.getenv("GEMINI_TIMEOUT_SEGUNDOS") or "60"
GEMINI_MAX_TENTATIVAS = os.getenv("GEMINI_MAX_TENTATIVAS") or "3"

# Login da demonstração (usuarios/demo.py)
# Sem usuários: as credenciais vêm do ambiente e a autenticação fica só na
# sessão (cookie assinado). Ausentes ou vazias, o login recusa todo acesso.

DEMO_LOGIN = os.getenv("DEMO_LOGIN")
DEMO_PASSWORD = os.getenv("DEMO_PASSWORD")
