# Generated by Django 6.1.1 on 2026-09-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('lancamento', 'numero'), name='unique_numero_parcela_por_lancamento')],
            },
        ),
    ]
